DEFAULT_DECISION_ORDER = [
    "deny",
    "manual_review",
    "condition_allow",
    "allow",
]

SUPPORTED_DECISIONS = set(DEFAULT_DECISION_ORDER)

EU_EEA_COUNTRIES = {
    "AT",
    "BE",
    "BG",
    "HR",
    "CY",
    "CZ",
    "DK",
    "EE",
    "FI",
    "FR",
    "DE",
    "GR",
    "HU",
    "IS",
    "IE",
    "IT",
    "LV",
    "LI",
    "LT",
    "LU",
    "MT",
    "NL",
    "NO",
    "PL",
    "PT",
    "RO",
    "SK",
    "SI",
    "ES",
    "SE",
}

AWS_REGION_TO_COUNTRY = {
    "af-south-1": "ZA",
    "ap-east-1": "HK",
    "ap-northeast-1": "JP",
    "ap-northeast-2": "KR",
    "ap-northeast-3": "JP",
    "ap-south-1": "IN",
    "ap-south-2": "IN",
    "ap-southeast-1": "SG",
    "ap-southeast-2": "AU",
    "ap-southeast-3": "ID",
    "ap-southeast-4": "AU",
    "ca-central-1": "CA",
    "ca-west-1": "CA",
    "eu-central-1": "DE",
    "eu-central-2": "CH",
    "eu-north-1": "SE",
    "eu-south-1": "IT",
    "eu-south-2": "ES",
    "eu-west-1": "IE",
    "eu-west-2": "UK",
    "eu-west-3": "FR",
    "il-central-1": "IL",
    "me-central-1": "AE",
    "me-south-1": "BH",
    "sa-east-1": "BR",
    "sa-riyadh-dc": "SA",
    "sa-jeddah-dc": "SA",
    "sa-dammam-dc": "SA",
    "us-east-1": "US",
    "us-east-2": "US",
    "us-west-1": "US",
    "us-west-2": "US",
}

EU_ADEQUACY_COUNTRIES = {
    "AD",
    "AR",
    "CA",
    "FO",
    "GG",
    "IL",
    "IM",
    "JP",
    "JE",
    "KR",
    "NZ",
    "CH",
    "UK",
    "UY",
}

FIELD_LABELS_KO = {
    "access_control_in_place": "접근통제",
    "adequacy_decision_exists": "적정성 결정 여부",
    "adequate_protection_confirmed": "적정 보호 수준 확인",
    "appropriate_safeguards_available": "적절한 보호조치 확보 여부",
    "baseline_security_controls_ready": "기본 보안 통제 충족 여부",
    "bcr_in_place": "BCR 체결 여부",
    "breach_notification_ready_72h": "72시간 내 침해 신고 준비",
    "binding_common_rules_approved": "승인된 공통구속규칙",
    "breach_response_72h_ready": "72시간 내 침해 대응 준비",
    "certification_or_code_in_place": "인증 또는 행동강령 보호조치",
    "contains_sensitive_data": "민감정보 포함 여부",
    "consent_withdrawal_process_ready": "동의 철회 대응 절차",
    "controller_processor_roles_defined": "컨트롤러·프로세서 역할 정의",
    "current_region": "현재 처리 리전",
    "data_accuracy_review_completed": "개인정보 정확성 점검",
    "data_minimized": "데이터 최소화",
    "data_subject_connection": "정보주체와 사우디 연결성",
    "data_subject_region": "정보주체 지역",
    "data_subject_rights_process_ready": "정보주체 권리 대응 절차",
    "data_subject_rights_request_ready": "정보주체 권리 요청 대응",
    "dataset_name": "데이터셋 이름",
    "derogation_type": "예외 이전 유형",
    "derogation_used": "제49조 예외 이전 사용 여부",
    "dpa_in_place": "DPA 체결 여부",
    "dpo_assigned": "개인정보 보호 책임자 지정",
    "dpo_required": "개인정보 보호 책임자 필요 여부",
    "dpia_completed": "DPIA 완료",
    "dpia_required": "DPIA 필요 여부",
    "encryption_at_rest": "저장 시 암호화",
    "encryption_in_transit": "전송 시 암호화",
    "incident_response_in_place": "침해 대응 절차",
    "is_third_country_transfer": "제3국 이전 여부",
    "lawful_basis": "적법 근거",
    "explicit_consent_for_sensitive_data": "민감정보 명시적 동의",
    "other_safeguards_in_place": "기타 제46조 보호조치",
    "privacy_notice_updated": "개인정보 처리방침 최신화",
    "privacy_notice_available": "개인정보 고지 제공",
    "processing_impact_assessment_completed": "처리 영향평가 완료",
    "processing_legal_basis": "처리 적법 근거",
    "processing_purpose_defined": "처리 목적 정의",
    "privacy_by_design_review_completed": "프라이버시 설계 검토 완료",
    "processor_sufficient_guarantees": "수탁자 충분한 보증",
    "processor_agreement_in_place": "프로세서 계약 체결",
    "processor_compliance_verified": "프로세서 준수 검증",
    "records_of_processing_exists": "처리 활동 기록부",
    "retention_period_defined": "보관기간 정의",
    "scc_in_place": "SCC 체결 여부",
    "special_category_condition_met": "민감정보 예외 요건 충족",
    "standard_contractual_clauses_in_place": "표준계약조항 체결",
    "subprocessor_controls_in_place": "하위처리자 통제",
    "subprocessor_or_onward_transfer_controls": "하위처리자·재이전 통제",
    "supplemental_measures_documented": "보완조치 문서화",
    "target_country": "대상 국가",
    "target_country_known": "대상 국가 식별 여부",
    "target_region": "대상 리전",
    "transfer_exception_type": "사우디 국외이전 예외 유형",
    "transfer_exception_used": "사우디 국외이전 예외 사용 여부",
    "transfer_disclosed_to_subject": "국외 이전 고지",
    "transfer_documented_in_ropa": "이전 사항 ROPA 반영",
    "transfer_impact_assessment_completed": "이전 영향 평가 완료",
    "transfer_outside_kingdom": "사우디 기준 국외 이전 여부",
    "transfer_risk_assessment_completed": "국외이전 위험평가 완료",
    "transfer_risk_assessment_required": "국외이전 위험평가 필요 여부",
    "transfer_safeguards_available": "이전 보호조치 확보 여부",
    "uses_processor": "외부 처리자 사용 여부",
    "large_scale_or_continuous_transfer": "대규모 또는 지속적 이전",
}
